client_id = "client2"
region = "us-west-1"
aws_access_key = "sdfgsdfg"
aws_secret_key = "asdfsdfg"
rds_instance_class = "db.t3.large"
rds_allocated_storage = 100
rds_engine_version = "8.0"
rds_username = "admin"
rds_password = "verysecurepassword"
rds_subnet_ids = ["subnet-12345678", "subnet-87654321"]
rds_security_group_ids = ["sg-12345678"]
rds_multi_az = true
rds_delete_automation_retention_period = 7